# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkingTime.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WorkingTime(object):
    def setupUi(self, WorkingTime):
        WorkingTime.setObjectName("WorkingTime")
        WorkingTime.resize(799, 753)
        self.centralwidget = QtWidgets.QWidget(WorkingTime)
        self.centralwidget.setObjectName("centralwidget")
        self._tablePresentEmployee = QtWidgets.QTableWidget(self.centralwidget)
        self._tablePresentEmployee.setGeometry(QtCore.QRect(20, 90, 371, 491))
        self._tablePresentEmployee.setObjectName("_tablePresentEmployee")
        self._tablePresentEmployee.setColumnCount(0)
        self._tablePresentEmployee.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self._tableTimeWorked = QtWidgets.QTableWidget(self.centralwidget)
        self._tableTimeWorked.setGeometry(QtCore.QRect(410, 90, 371, 491))
        self._tableTimeWorked.setObjectName("_tableTimeWorked")
        self._tableTimeWorked.setColumnCount(0)
        self._tableTimeWorked.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self._fromTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self._fromTimeEdit.setGeometry(QtCore.QRect(460, 50, 131, 22))
        self._fromTimeEdit.setObjectName("_fromTimeEdit")
        self._toTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self._toTimeEdit.setGeometry(QtCore.QRect(650, 50, 131, 22))
        self._toTimeEdit.setObjectName("_toTimeEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 50, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 50, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self._addUserButton = QtWidgets.QPushButton(self.centralwidget)
        self._addUserButton.setGeometry(QtCore.QRect(340, 680, 111, 31))
        self._addUserButton.setObjectName("_addUserButton")
        self._firstNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self._firstNameEdit.setGeometry(QtCore.QRect(140, 620, 151, 20))
        self._firstNameEdit.setObjectName("_firstNameEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 590, 821, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 0, 20, 601))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 620, 61, 16))
        self.label_5.setObjectName("label_5")
        self._lastNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self._lastNameEdit.setGeometry(QtCore.QRect(240, 650, 151, 20))
        self._lastNameEdit.setObjectName("_lastNameEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 650, 61, 16))
        self.label_6.setObjectName("label_6")
        self._emailEdit = QtWidgets.QLineEdit(self.centralwidget)
        self._emailEdit.setGeometry(QtCore.QRect(350, 620, 151, 20))
        self._emailEdit.setObjectName("_emailEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 620, 31, 16))
        self.label_7.setObjectName("label_7")
        self._passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self._passwordEdit.setGeometry(QtCore.QRect(450, 650, 151, 20))
        self._passwordEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self._passwordEdit.setObjectName("_passwordEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 650, 51, 16))
        self.label_8.setObjectName("label_8")
        self._tagIdEdit = QtWidgets.QLineEdit(self.centralwidget)
        self._tagIdEdit.setGeometry(QtCore.QRect(540, 620, 151, 20))
        self._tagIdEdit.setText("")
        self._tagIdEdit.setObjectName("_tagIdEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(510, 620, 31, 16))
        self.label_9.setObjectName("label_9")
        WorkingTime.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WorkingTime)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        WorkingTime.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WorkingTime)
        self.statusbar.setObjectName("statusbar")
        WorkingTime.setStatusBar(self.statusbar)

        self.retranslateUi(WorkingTime)
        QtCore.QMetaObject.connectSlotsByName(WorkingTime)

    def retranslateUi(self, WorkingTime):
        _translate = QtCore.QCoreApplication.translate
        WorkingTime.setWindowTitle(_translate("WorkingTime", "WorkingTime"))
        self.label.setText(_translate("WorkingTime", "Present Employees"))
        self.label_2.setText(_translate("WorkingTime", "Time Worked"))
        self.label_3.setText(_translate("WorkingTime", "From:"))
        self.label_4.setText(_translate("WorkingTime", "To:"))
        self._addUserButton.setText(_translate("WorkingTime", "Add User"))
        self.label_5.setText(_translate("WorkingTime", "First Name:"))
        self.label_6.setText(_translate("WorkingTime", "Last Name:"))
        self.label_7.setText(_translate("WorkingTime", "Email:"))
        self.label_8.setText(_translate("WorkingTime", "Password:"))
        self.label_9.setText(_translate("WorkingTime", "TagId:"))

